ignores:
  - node_modules/**
  - dist/**
  - .astro/**

config:
  # https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
  line-length:
    line_length: 100
    tables: false
  # https://github.com/DavidAnson/markdownlint/blob/main/doc/md060.md
  table-column-style:
    style: aligned
