#!/usr/bin/env python3
"""Generate the reviewed-rule agent instruction pack."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from textwrap import wrap


ROOT = Path(__file__).resolve().parents[1]
RULES_DIR = ROOT / "rules"
OUTPUT = ROOT / "snippets" / "agents" / "rules.md"


@dataclass(frozen=True)
class Rule:
    id: str
    domain: str
    status: str
    instruction: str
    path: Path


def metadata(text: str, name: str) -> str:
    match = re.search(rf"^- {re.escape(name)}: `([^`]+)`$", text, re.MULTILINE)
    return match.group(1) if match else ""


def section(text: str, name: str) -> str:
    match = re.search(
        rf"^## {re.escape(name)}\n\n(.*?)(?=\n\n## |\Z)",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        return ""
    return " ".join(match.group(1).split())


def domain_name(domain_dir: Path) -> str:
    readme = domain_dir / "README.md"
    if not readme.exists():
        return domain_dir.name.replace("-", " ").title()
    first_line = readme.read_text().splitlines()[0]
    if first_line.startswith("# "):
        return first_line[2:]
    return domain_dir.name.replace("-", " ").title()


def discover_rules() -> list[Rule]:
    rules: list[Rule] = []
    for path in sorted(RULES_DIR.glob("*/*.md")):
        if path.name == "README.md":
            continue
        text = path.read_text()
        rule = Rule(
            id=metadata(text, "ID"),
            domain=metadata(text, "Domain"),
            status=metadata(text, "Status"),
            instruction=section(text, "Agent Instruction"),
            path=path,
        )
        missing = [
            name
            for name, value in [
                ("ID", rule.id),
                ("Domain", rule.domain),
                ("Status", rule.status),
                ("Agent Instruction", rule.instruction),
            ]
            if not value
        ]
        if missing:
            joined = ", ".join(missing)
            raise SystemExit(f"{path.relative_to(ROOT)} is missing {joined}")
        rules.append(rule)
    return rules


def wrap_bullet(text: str) -> list[str]:
    return wrap(
        text,
        width=100,
        initial_indent="- ",
        subsequent_indent="  ",
        break_long_words=False,
        break_on_hyphens=False,
    )


def render(rules: list[Rule]) -> str:
    reviewed = [rule for rule in rules if rule.status == "reviewed"]
    by_domain: dict[str, list[Rule]] = {}
    for rule in reviewed:
        by_domain.setdefault(rule.domain, []).append(rule)
    for domain_rules in by_domain.values():
        domain_rules.sort(key=lambda rule: rule.id)

    lines = [
        "# Reviewed Rule Agent Pack",
        "",
        "## Metadata",
        "",
        "- Name: `Reviewed Rule Agent Pack`",
        "- ID: `agent-reviewed-rule-pack`",
        "- Summary: `Generated compact execution surface for every reviewed rule. The pack gives agents",
        "  stable rule IDs and instructions while leaving rationale, examples, and deeper context in the",
        "  canonical rule files.`",
        "- Status: `reviewed`",
        "- Audience: `agents`",
        "- Topics: `rules, agent-workflow, generated-artifacts, downstream-adoption`",
        "- Tags: `agents, snippets, rules, generated`",
        "- Related: `rules/README.md, guides/coding-agents.md, mechanisms/guidance-generation-and-audit.md`",
        "",
        "This is the compressed agent execution surface for reviewed rules. It intentionally omits",
        "rationale, examples, tradeoff detail, and links. Use rule IDs as stable handles when a",
        "handoff needs to identify which instruction drove a decision.",
        "",
        "For implementation work, apply the instructions that match the repo and task.",
        "",
        "Generated by `scripts/generate_agent_rules.py`. Edit rule files, then regenerate this pack.",
        "",
        "## Instructions",
        "",
    ]

    for domain in sorted(by_domain):
        lines.extend([f"### {domain_name(RULES_DIR / domain)}", ""])
        for rule in by_domain[domain]:
            instruction = f"`{rule.id}`: {rule.instruction}"
            lines.extend(wrap_bullet(instruction))
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if snippets/agents/rules.md is not up to date",
    )
    args = parser.parse_args()

    rendered = render(discover_rules())
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
